### ISSUE TITLE
Fake Monet on A12 non-pixel phones

### ISSUE THREAD

**Issue by mxkmn** [sadellie/themmo#16]
Hi!

Looks like Monet is a Pixel exclusive and not available on AOSP smartphones on Android 12 (check [thread](https://www.reddit.com/r/SonyXperia/comments/tdwqk3/android_12_ui_on_xperia_5_ii_is_absolutely_ugly/) for more info). It looks like giving the option to choose the adaptive theme type is necessary on this version.

However, so as not to break the current library behaviour and take away unnecessary choice, I can help get the standard (boring blue) colours from my Xperia II with Android 12. Are you ready to add some checks to the library to solve the problem?

**Comment by sadellie** [comment]
I'm not sure that you understood this project. This is a theming library for Jetpack Compose. App developers use it in their app.

For example, I use it in my app:
https://github.com/sadellie/unitto

Developers can use Custom color option to generate color schemes. It's already implemented.

**Comment by mxkmn** [comment]
You didn't get it right.

Not all phones provide dynamic colours for the A12. Here's what I get with the yellow wallpaper on the Xperia 5 II:
![image](https://github.com/sadellie/themmo/assets/75564533/a9b41f67-f11f-49f9-ae39-7b00a8fcd941)

I would like to get yellow in the app with Themmo if the library understands that ROM does not provide Monet. This behaviour is implemented on Android 8.1-11, but not on 12 now.

**Comment by sadellie** [comment]
Unfortunately, that's difficult to implement. Currently I think there are 2 ways to solve this.

1. Hard code ROM names

2. Compare 2 colors:
- Primary wallpaper color
- Primary color from dynamicLightColorScheme/dynamicDarkColorScheme
And decide from that whether fake monet needs to be used.

Both solutions are very inefficient and can lead to false positive situations.

The best solution is to take advantage of Themmo's ability to generate color scheme using fake Monet. Developers can simply get primary color from wallpaper and pass it to Themmo as a custom color. With this approach fake Monet will be used.

**Comment by mxkmn** [comment]
> Developers can simply get primary color from wallpaper and pass it to Themmo as a custom color.

So, how to implement this?

**Comment by sadellie** [comment]
Something like this will work.
```kotlin
// Needs API 27 or higher
val wallpaperColors = WallpaperManager.getInstance(context).getWallpaperColors(WallpaperManager.FLAG_SYSTEM)
// Convert into Color
val primary = Color(
                    red = wallpaperColors.primaryColor.red(),
                    green = wallpaperColors.primaryColor.green(),
                    blue = wallpaperColors.primaryColor.blue()
                )
// Use ThemmoController that is provided by Themmo composable
themmoController.setCustomColor(primary)
```
